# Generated by Django 3.2.6 on 2021-11-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speaker', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('number_of_views', models.PositiveIntegerField()),
                ('transcript', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
